language: cpp

compiler:
  - clang
  - gcc
cache:
  - apt
os:
  - osx
  - linux

before_install:
  # update packages
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y build-essential libtool libpcap0.8 libpcap-dev ; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.3.2.tar.gz ; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xzf cmake-3.3.2.tar.gz ; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd cmake-3.3.2 && ./configure && make && sudo make install && cd .. ; fi
       
before_script:  
  - cmake .

script:
  - make
  - ./bin/packetmachine-static-test
  - ./bin/packetmachine-shared-test

